In [ ]:
import torch
torch.__version__

'2.9.0+cu126'

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
import numpy as np
scalar_np = np.array(7)
scalar_np

array(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                       [[13, 14, 15],
                        [16, 17, 18]]])
tensor.shape

torch.Size([3, 2, 3])

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6321, 0.7400, 0.2366, 0.9606],
         [0.2322, 0.5968, 0.6630, 0.4713],
         [0.3043, 0.1522, 0.9751, 0.8520]]),
 torch.float32)

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)