In [1]:
# Understanding Numpy

import numpy as np
import matplotlib.pyplot as plt
import time

In [2]:
# Check Numpy version
print(f"Numpy version: {np.__version__}")

Numpy version: 1.26.4


In [3]:
# Display setting for clearer output
np.set_printoptions(precision=3, suppress=True)

Creating Numpy Arrays

In [4]:
# Creating arrays from Python lists
# 1D array: A simple sequence of numbers

arr1d = np.array([1, 2, 3, 4, 5])

# 2D array: Think of this as a matrix or table with rows and columns
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6]])

# 3D array: Like a steak of 2D arrays - useful for images, time series, etc.
arr3d = np.array([[[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]])

print("1D array:", arr1d)
print("2D array:\n", arr2d)
print("3D array:\n", arr3d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Creating Special Arrays in Numpy

In [5]:
# Creating arrays filled with zeros - useful for initializing arrays
# Shape (3, 4) means 3 rows and 4 columns
zeros = np.zeros((3, 4))

# Creating arrays filled with ones - often used as starting points
ones = np.ones((2, 3, 4))      # 3D array: 2 layers, 3 rows, 4 columns

# Empty array - faster than zeros/ones but contains random values
# Use when you'll immediately fill the array with real data
empty = np.empty((2, 2))

print("Zeros array (3x4):\n", zeros)
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n", empty)

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[0. 0.]
 [0. 0.]]


NOTE: zeros() and ones() are memory-efficient ways to create arrays of specific sizes. empty() is fastest but contains garbage values, so only use it when you'll immediately overwrite the cotents.

In [6]:
# Range arrays - like Python's range() but more powerful
range_arr = np.arange(0, 10, 2)  # Start at 0, end before 10, step by 2: [0, 2, 4, 6, 8]
print("Range array:", range_arr)

# Linearly spaced arrays - divide a range into equal parts
# From 0 to 1 with exactly 5 points (including endpoints)
linspace_arr = np.linspace(0, 1, 5)
print("Linspace array:", linspace_arr)

# Logarithmically spaced arrays - useful for scientific data
# From 10^0 to 10^2 (1 to 100) with 5 points
logspace_arr = np.logspace(0, 2, 5)
print("Logspace array:", logspace_arr)

Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


arange() works like Pyhton's range() but returns a Numpy array and works with floats.
linspace() divides a range into equal segments - useful for plotting smooth curves.
logspace() creates points that are evenly spaced on a logarithmic scale.

In [7]:
# Identity matrix - diagonal of ones, zeros elsewhere
# Essential for linear algebra operations
identity = np.eye(4)    # 4x4 identity matrix

# Diagonal matrix - put values on the diagonal
diagonal = np.diag([1, 2, 3, 4]) # Diagonal matrix with specified diagonal values

# Array filled with a specific value
full_arr = np.full((3, 3), 7)      # 3x3 array filled with 7s

print("Identity matrix:\n", identity)
print("Diagonal matrix:\n", diagonal)
print("Full array (filled with 7s):\n", full_arr)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7s):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


Numpy Data types (dtypes)


Understanding data types is crucial for memory efficiency and numerical precision.

In [8]:
# Explicit data types - control memory usage and precision
int_arr = np.array([1, 2, 3], dtype=np.int32)    # 32-bit integers
float_arr = np.array([1, 2, 3], dtype=np.float64) # 64-bit floats (double precision)
bool_arr = np.array([True, False, True], dtype=np.bool_)     # Boolean values

# Types conversion - control dtype of existing array
converted = int_arr.astype(np.float32)   # Convert to 32-bit floats

print("Integer array:", int_arr.dtype)
print("Float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr)
print("Converted array dtype:", converted.dtype)

# Memory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

Integer array: int32
Float array dtype: float64
Boolean array dtype: [ True False  True]
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 8 bytes per element


Array Properties & Attributes

Understanding array properties helps you work effectively with your data and debug issue

In [9]:
# Create a sample 3D array for demonstration
# Think of this as 3 layers, each with 4 rows 5 columns
arr = np.random.randn(3, 4, 5)

# Shape: The dimensions of the array (layers, rows, columns)
print("Shape:", arr.shape)

# Size: Total number of elements (3 x 4 x 5 = 60)
print("Size:", arr.size)

# Ndim: Number of dimensions (3D in this case)
print("Ndim:", arr.ndim)

# Dtype: Data type of elements
print("Dtype:", arr.dtype)

# Itemize: Memory size of each element in bytes
print("Itemsize:", arr.itemsize)   # 8 bytes for float64

# Total memory usage in bytes
print("Memory usage:", arr.nbytes, "bytes")     # size x itemsize
print("Memory usage:", arr.nbytes / 1024, "KB")   # Convert to KB

Shape: (3, 4, 5)
Size: 60
Ndim: 3
Dtype: float64
Itemsize: 8
Memory usage: 480 bytes
Memory usage: 0.46875 KB


NOTE: These properties are essential for understanding your data's structure and memory requirements. Large datasets require careful attention to memory usage.

Array Indexing & Slicing

Basic Indexing - Accessing Individual Elements

** Numpy indexing is similar to Python lists but more powerful for multi-dimensional arrays

In [10]:
# 1D array indexing - similar to Python lists
arr1d = np.array([10, 20, 30, 40, 50])

print("First element:", arr1d[0])    # Index 0: 10
print("Last element:", arr1d[-1])    # Negative indexing: 50
print("Slicing [1:4]:", arr1d[1:4])   # Elements 1, 2, 3: [20, 30, 40]
print("Every 2nd element:", arr1d[::2])  # Step of 2: [10, 30, 50]

First element: 10
Last element: 50
Slicing [1:4]: [20 30 40]
Every 2nd element: [10 30 50]


Negative indices count from the end (-1 is last element). Slicing uses [starts:stop:step] where stop is exclusive.

In [11]:
# 2D array indexing - row and column access
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Acess specific element [row, column]
print("Element at row 1, column 2:", arr2d[1, 2])       # 7

# Access entire rows or columns
print("First row:", arr2d[0, :])         # All columns of row 0
print("Second column:",  arr2d[:, 1])      # All rows of column 1

# Subarray slicing: [row_start:row_end, col_start:col_end]
print("Subarray (rows 1-2, cols 1-2):\n", arr2d[1:3, 1:3])

Element at row 1, column 2: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Subarray (rows 1-2, cols 1-2):
 [[ 6  7]
 [10 11]]


The comma seperates dimensons. : means "all elements along this dimenson". Slicing creates views of the original data when possible, not copies.

Advanced Indexing - Powerful Selection Methods

In [12]:
# Fancy indexing - use arrays of indices to select multiple elements
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])     # Select at positions 0, 2, 4
print("Fancy indexing:", arr[indices])   # [10, 30, 50]

# This is much more flexible than simple slicing
random_indices = np.array([4, 1, 3, 1])     # Can repeat and reorder
print("Random order:", arr[random_indices])   # [50, 20, 40, 20] 

Fancy indexing: [10 30 50]
Random order: [50 20 40 20]


Fancy indexing lets you select elements in any order, repeat elements, and select non-contiguous elements. Very useful for data smapling and reordering.

In [13]:
# 2D fancy indexing - select specific row/column combinations
arr2d = np.arange(12).reshape(3, 4)   # 3x4 array: [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
print("Original 2D array:\n", arr2d)

# Select elements at (row, col) pairs: (0, 1) and (2, 3)
rows = np.array([0, 2])
cols = np.array([1, 3])
print("Elements at (0, 1) and (2, 3):", arr2d[rows, cols])  # [1, 11]

# Select entire rows using fancy indexing
selected_rows = arr2d[[0, 2], :]    # Rows 0 and 2, all columns
print("Selected rows:\n", selected_rows)

Original 2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Elements at (0, 1) and (2, 3): [ 1 11]
Selected rows:
 [[ 0  1  2  3]
 [ 8  9 10 11]]


When you provide arrays for both dimensions, NumPy pairs them element-wise. This is different from slicing, which creates a rectangular subarray. 

**Array Reshaping & Manipulation**


- Reshaping changes how the same data is organized in memory without changing the actual values.

In [14]:
# Start with a 1D array
arr = np.arange(12)   # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print("Original 1D array:", arr)

# Reshape to 2D 3 rows x 4 columns
reshaped_2d = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_2d)

# reshape to 3D: 2 layers x 2 rows x 3 columns
reshaped_3d = arr.reshape(2, 2, 3)
print("Reshaped to 2x2x3:\n", reshaped_3d)

# Use -1 to let NumPy calculate one dimension automatically
auto__reshape = arr.reshape(4, -1)   # 4 rows, NumPy calculates columns
print("Auto-reshaped to 4x?:\n", auto__reshape)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x2x3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Auto-reshaped to 4x?:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The total number of elements must remain the same (12 in this case). Using -1 tells NumPy to calculate that dimension automatically. Reshaping creates a view when possible, not a copy.

In [15]:
# Flattening - convert multi-dimensional array to 1D
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# flatten() always returns a copy
flattened = arr2d.flatten()
print("Flattened (copy):", flattened)

# ravel() returns a view if possible (faster, memory efficient)
ravel = arr2d.ravel()
print("Ravel (view if possible):", ravel)

# Demonstrate the difference
arr2d[0, 0] = 999
print("After modifying original:")
print("Flattened (unchanged):", flattened)    # Copy is independent
print("Ravel (changed):", ravel)   # View reflects changes

Flattened (copy): [1 2 3 4 5 6]
Ravel (view if possible): [1 2 3 4 5 6]
After modifying original:
Flattened (unchanged): [1 2 3 4 5 6]
Ravel (changed): [999   2   3   4   5   6]


Use ravel() when you don't need to modify the flattened array independently. Use flatten() when you need a seperate copy that won't be affected by changes to the original.

Transposing and Swapping Axes

** Transposing is essential for matrix operations and changing data orientation.

In [16]:
# 2D transposition - flip rows and columns
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6]])
print("Original shape:", arr2d.shape)   # (2, 3)
print("Original:\n", arr2d)

print("Transposed shape:", arr2d.T.shape)  # (3, 2)
print("Transposed:\n", arr2d.T)

# Alternative transpose methods
print("Transpose method:\n", arr2d.transpose())

Original shape: (2, 3)
Original:
 [[1 2 3]
 [4 5 6]]
Transposed shape: (3, 2)
Transposed:
 [[1 4]
 [2 5]
 [3 6]]
Transpose method:
 [[1 4]
 [2 5]
 [3 6]]


Transposing swaps rows and columns. This is crucial for matrix multiplication and when you need to change data orientation (e.g., from samplesxfeatures to featuresxsamples)

In [17]:
# Higher-dimensional transposition 
arr3d = np.arange(24).reshape(2, 3, 4)  # 2 layers, 3 rows, 4 columns
print("Original 3D shape:", arr3d.shape)   # (2, 3, 4)

# Spcify new axis order: (axis0, axis1, axis2) -> (axis2, axis0, axis1)
transposed_3d = arr3d.transpose(2, 0, 1)
print("Transposed 3D shape:", transposed_3d.shape)  # (4, 2, 3)

# moveaxis is another way to rearrange axes
moved = np.moveaxis(arr3d, 0, -1)  # Move first axis to last position
print("Moveaxis result shape:", moved.shape)  # (3, 4, 2)

Original 3D shape: (2, 3, 4)
Transposed 3D shape: (4, 2, 3)
Moveaxis result shape: (3, 4, 2)


For 3D+ arrays, you specify the new order of axes. This is useful for reshaping data for different algorithms or visualization requirements.

Concatenating and Splitting Arrays

** Combining and dividing arrays is fundamental for data manipulation

In [18]:
# Conatenation - joining arrays along existing axes
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenating along different axes
concat_rows = np.concatenate([arr1, arr2], axis=0)   # Stack vertically (add rows)
concat_cols = np.concatenate([arr1, arr2], axis=1)   # Stack horizontally (add columns)

print("Original arrays:")
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated vertically (axis=0):\n", concat_rows)
print("Concatenated horizontally (axis=1):\n", concat_cols)

Original arrays:
Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Concatenated vertically (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated horizontally (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]


axis=0 means along rows (vertical stacking), axis=1 means along columns (horizontal stacking). Arrays must have compatible shapes along the non-concatenated dimensions.

In [19]:
# Convenient stacking functions
vstack_result = np.vstack([arr1, arr2])   # Same as concatenate with axis=0
hstack_result = np.hstack([arr1, arr2])   # Same as concatenate with axis=1
dstack_result = np.dstack([arr1, arr2])   # Stack along depth (3rd dimension)

print("vstack (vertical):\n", vstack_result)
print("hstack (horizontal):\n", hstack_result)
print("dstack shape:", dstack_result.shape)    # Creates 3D array

# Splitting arrays - opposite of concatenation
arr = np.arange(12).reshape(3, 4)
split_arrays = np.split(arr, 3, axis=0)    # Split into 3 parts along rows
print("Original array for splitting:\n", arr)
print("Split into 3 parts along rows:")
for i, split_part in enumerate(split_arrays):
    print(f"Part {i}:\n", split_part)

vstack (vertical):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack (horizontal):
 [[1 2 5 6]
 [3 4 7 8]]
dstack shape: (2, 2, 2)
Original array for splitting:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Split into 3 parts along rows:
Part 0:
 [[0 1 2 3]]
Part 1:
 [[4 5 6 7]]
Part 2:
 [[ 8  9 10 11]]


Stacking functions are shortcuts for concatenation. Splitting divides an array into equal parts - useful for creating training/validation sets or processing data in chunks. 

**Mathematical Operations**

**Elements-wise Operations - The Power of Vectorization**

- NumPy's biggest advantage is performing operations on entire arrays without writing loop.

In [20]:
# Basic arithmetic operations work element-by-element
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print("Array 1:", arr1)
print("Array 2:", arr2)

# All operations happen element-wise automatically
print("Addition:", arr1 + arr2)    # [11, 22, 33, 44]
print("Subtraction:", arr2 - arr1) # [9, 18, 27, 36]
print("Multiplication:", arr1 * arr2)  # [10, 40, 90, 160]
print("Division:", arr1 / arr2)        # [10, 10, 10, 10]
print("Power:", arr1 ** 2)            # [1, 4, 9, 16]
print("Modulo:", arr2 % 3)           # [1, 2, 0, 1]

Array 1: [1 2 3 4]
Array 2: [10 20 30 40]
Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]
Power: [ 1  4  9 16]
Modulo: [1 2 0 1]


This vectorization is much  faster than Python loops because the operations are implemented in optimized C code. Each operation applies to corresponding elements.

In [21]:
# Opeartions with scalars - broadcasting in action
print("Scalar operations:")
print("Add 10 to all elements:", arr1 + 10)   # [11, 12, 13, 14]
print("Multiply all by 3:", arr1 * 3)     # [3, 6, 9, 12]
print("Divide all by 2:", arr1 / 2)       # [0.5, 1, 1.5, 2]

# Compound operations
result = (arr1 + 5) * 2 - 1              # ((arr1 + 5) * 2) - 1
print("Compound operation (arr1 + 5) * 2 -1:", result)

Scalar operations:
Add 10 to all elements: [11 12 13 14]
Multiply all by 3: [ 3  6  9 12]
Divide all by 2: [0.5 1.  1.5 2. ]
Compound operation (arr1 + 5) * 2 -1: [11 13 15 17]


When you operate on arrays with scalars, the scalar is automatically "broadcast" to match the array shape. This is much more readable and efficient than manual loops.

**Mathematical Functions - Beyond Basic Arithmetic**

- NumPy provides vectorized versions of most mathematical function

In [22]:
# Common mathematical functions
arr = np.array([1, 4, 9, 16, 25])
print("Original array:", arr)

# Square roots and powers
print("Square root:", np.sqrt(arr))     # [1, 2, 3, 4, 5]
print("Square:", np.square(arr))       # [1, 16, 81, 256, 625]

# Exponential and logarithmic functions
small_arr = np.array([1, 2, 3])
print("Exponential:", np.exp(small_arr))    # [e^1, e^2, e^3]
print("Natural log:", np.log(arr))        # in(arr)
print("Log base 10:", np.log10(arr))
print("Log base 2:", np.log2(arr))

Original array: [ 1  4  9 16 25]
Square root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]
Exponential: [ 2.718  7.389 20.086]
Natural log: [0.    1.386 2.197 2.773 3.219]
Log base 10: [0.    0.602 0.954 1.204 1.398]
Log base 2: [0.    2.    3.17  4.    4.644]


These functions are much faster than applying Python's math functions in a loop. They also habdle edge cases (like log of zero) more gracefully.

In [23]:
# Trigonometric functions - essential for signal processing and geometry
angles = np.array([0, np.pi/4, np.pi/2, np.pi])
print("Angles (radians:)", angles)
print("SIne:", np.sin(angles))     # [0, √2/2, 1, 0]
print("Cosine:,", np.cos(angles))  # [1, √2/2, 0, -1]
print("Tangent:", np.tan(angles))  # [0, 1, ∞, 0]

# Convert degrees to radians
degrees = np.array([0, 45, 90, 180])
radians = np.deg2rad(degrees)
print("Degree to radians:", radians)

Angles (radians:) [0.    0.785 1.571 3.142]
SIne: [0.    0.707 1.    0.   ]
Cosine:, [ 1.     0.707  0.    -1.   ]
Tangent: [ 0.000e+00  1.000e+00  1.633e+16 -1.225e-16]
Degree to radians: [0.    0.785 1.571 3.142]


Trigonometric functions expect angles in radians. Use deg2rad() and rad2deg() for conversions. These fucntions are essential for Signal precessing, Computer graphics, and Physics simulations.

In [24]:
# Rounding and comparison functions
decimals = np.array([1.234, 5.678, 9.999, -2.345])
print("Original decimals:", decimals)

print("Round to 2 places:", np.round(decimals, 2))
print("Floor (round down):", np.floor(decimals))    # [1, 5, 9, -3]
print("Ceiling (round up):", np.ceil(decimals))   # [2, 6, 10, -2]
print("Truncate (toward zero):", np.trunc(decimals))  # [1, 5, 9, -2]

# Absolute values and sign
print("Absolute values:", np.abs(decimals))
print("Sign (-1, 0, or 1):", np.sign(decimals))

Original decimals: [ 1.234  5.678  9.999 -2.345]
Round to 2 places: [ 1.23  5.68 10.   -2.35]
Floor (round down): [ 1.  5.  9. -3.]
Ceiling (round up): [ 2.  6. 10. -2.]
Truncate (toward zero): [ 1.  5.  9. -2.]
Absolute values: [1.234 5.678 9.999 2.345]
Sign (-1, 0, or 1): [ 1.  1.  1. -1.]


Different rounding functions serve different purposes. floor() always rounds down, ceil() always rounds up, trunc() removes the decimal part, and round() rounds to nearest value.

**Aggregate Functions - Summarizing Your Data**

- Aggregate functions reduce arrays to summary statistics

In [25]:
# Create a 2D array for demonstration
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Sample array:\n", arr)

# Aggregate across entire array
print("Sum of all elements:", np.sum(arr))   # 45
print("Mean of all elements:", np.mean(arr))  # 5.0
print("Standard deviation:", np.std(arr))     # 2.58
print("Minimum value:", np.min(arr))          # 1
print("Maximum value:",  np.max(arr))         # 9 

Sample array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
Mean of all elements: 5.0
Standard deviation: 2.581988897471611
Minimum value: 1
Maximum value: 9


When you don't specify an axis, these functions operate on the flattened array, giving you a single summary value for the dataset.

In [26]:
# Axis-specific aggregation - this is where NumPy!
print("Sum along axis 0 (columns):", np.sum(arr, axis=0))   # [12, 15, 18]
print("Sum along axis 1 (rows):", np.sum(arr, axis=1))      # [6, 15, 24]

print("Mean along axis 0:", np.mean(arr, axis=0))          # [4, 5, 6]
print("Mean along axis 1:", np.mean(arr, axis=1))          # [2, 5, 8]

# Finding positions of extreme values
print("Position of max (flattened):", np.argmax(arr))   # 8 (element 9 at position 8)
print("Position of max along axis 0:", np.argmax(arr, axis=0))   # [2, 2, 2]
print("Position of max along axis 1:", np.argmax(arr, axis=1))   # [2, 2, 2]

Sum along axis 0 (columns): [12 15 18]
Sum along axis 1 (rows): [ 6 15 24]
Mean along axis 0: [4. 5. 6.]
Mean along axis 1: [2. 5. 8.]
Position of max (flattened): 8
Position of max along axis 0: [2 2 2]
Position of max along axis 1: [2 2 2]


- axis=0: Operations go "down" the rows (result has same number of columns)
- axis=1: Operations go "across" the columns (result has same number of rows)
- argmax/argmin return indices, not values

**Broadcasting**

- Broadcasting is NumPy's way of performing operations on arrays with different shapes without explicitly reshaping them. This is one of NumPy's most powerful features

In [27]:
# Broadcasting examples - arrays don't need the same shape!
scalar = 5
arr1d = np.array([1, 2, 3, 4])
arr2d = np.array([[10], [20], [30]])   # Column vector

print("Scalar:", scalar)
print("1D array:", arr1d)
print("2D array (column vector):\n", arr2d)

# Scalar broadcasts to any shape
result1 = scalar + arr1d
print("Scalar + 1D array:", result1)     # [6, 7, 8, 9]

# 2D + 1D broadcasting
result2 = arr2d + arr1d
print("2D + 1D broadcasting:\n", result2)

Scalar: 5
1D array: [1 2 3 4]
2D array (column vector):
 [[10]
 [20]
 [30]]
Scalar + 1D array: [6 7 8 9]
2D + 1D broadcasting:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


- Broadcasting follows these rules:
- Start from the trailing (rightmost) dimensions
- Dimensions are compatible if they're equal or one is 1
- Missing dimensions are assumed to be 1

In [28]:
# Visualizing broadcasting step by step
a = np.arange(4).reshape(4, 1)     # Shape: (4, 1)
b = np.arange(5).reshape(1, 5)     # Shape: (1, 5)

print("Array a (4x1):\n", a)
print("Array b (1x5):\n", b)

# Broadcasting creates a 4x5 result
result = a + b                          # Result shape: (4, 5)
print("Broadcasting result (4x5:\n)", result)
print("Result shape:", result.shape)

Array a (4x1):
 [[0]
 [1]
 [2]
 [3]]
Array b (1x5):
 [[0 1 2 3 4]]
Broadcasting result (4x5:
) [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
Result shape: (4, 5)


Array a gets broadcast horizontally, array b gets broadcast vertically. This creates all pairwise combinations without storing redundant data.

In [29]:
# Manual broadcasting with newaxis
arr = np.array([1, 2, 3])     
print("Original array shape:", arr.shape)     # (3,)

# Convert to column vector
column_vector = arr[:, np.newaxis]      # Same as arr.reshape(-1, 1)
print("Column vector shape:", column_vector.shape)   # (3, 1)
print("Column vector:\n", column_vector)

# Convert to row vector (usually not needed - 1D arrays broadcast as rows)
row_vector = arr[np.newaxis, :]                  # Same as arr.reshape(1, -1)
print("Row vector shape:", row_vector.shape)     # (1, 3)

Original array shape: (3,)
Column vector shape: (3, 1)
Column vector:
 [[1]
 [2]
 [3]]
Row vector shape: (1, 3)


np.newaxis is an alias for None and adds a new axis of length 1. This gives you explicit control over broadcasting behavior

**Common Broadcasting Patterns**

In [30]:
# Pattern 1: Centering data (subtract mean from each column)
data = np.random.randn(5, 3)    # 5 samples, 3 features
print("Original data shape:", data.shape)
print("Original data:\n", data)

# Calculate mean of each column (feature)
column_means = np.mean(data, axis=0)  # Shape (3,)
print("Column means:", column_means)

# Subtract mean from each column (broadcasting!)
centered_data = data - column_means   # (5, 3) - (3,) -> (5, 3)
print("Centered data:\n", centered_data)
print("New column means (should be ~0):", np.mean(centered_data, axis=0))

Original data shape: (5, 3)
Original data:
 [[ 0.183 -0.842  0.005]
 [-0.398 -0.415  0.23 ]
 [-0.088  1.549  0.264]
 [ 0.19  -0.446  1.563]
 [-0.086  0.565 -0.006]]
Column means: [-0.04   0.082  0.411]
Centered data:
 [[ 0.223 -0.924 -0.406]
 [-0.358 -0.497 -0.181]
 [-0.048  1.466 -0.147]
 [ 0.229 -0.529  1.152]
 [-0.046  0.483 -0.417]]
New column means (should be ~0): [-0. -0. -0.]


This is a common preprocessing step in machine learning. The column means broadcast across all rows automatically.

In [31]:
# Pattern 2: Normalizing by row sums (useful for probabilities)
data = np.random.rand(4, 3)   # Random data
print("Random data:\n", data)

# Calculate row sums
row_sums = np.sum(data, axis=1, keepdims=True)   # Shape: (4, 1)
print("Row sums shape:", row_sums.shape)
print("Row sums:\n", row_sums)

# Normalize each row to sum to 1
normalized = data / row_sums          # (4, 3) / (4, 1) broadcasts
print("Normalized data (rows sum to 1):\n", normalized)
print("Row sums after normalization:", np.sum(normalized,axis=1))

Random data:
 [[0.703 0.649 0.712]
 [0.23  0.905 0.439]
 [0.061 0.857 0.906]
 [0.217 0.473 0.125]]
Row sums shape: (4, 1)
Row sums:
 [[2.064]
 [1.573]
 [1.824]
 [0.815]]
Normalized data (rows sum to 1):
 [[0.341 0.314 0.345]
 [0.146 0.575 0.279]
 [0.033 0.47  0.497]
 [0.267 0.581 0.153]]
Row sums after normalization: [1. 1. 1. 1.]


keepdims=True preserves the dimension as size 1, making broadcasting explicit and avoiding shape errors.