**1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.**


In [82]:
import numpy as np

arr = np.random.randint(51, size=(6, 6))
arr


array([[29, 33, 29, 28, 20, 44],
       [17, 30, 39, 35, 50, 38],
       [48,  5, 13, 42, 24, 22],
       [11, 50, 12,  9,  4, 16],
       [22, 27, 10, 19, 35, 26],
       [20, 36, 11, 43, 41,  8]])

**2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.**

In [83]:
print("First 2 rows:\n", arr[:2])
print("Last 3 columns:\n", arr[:, 3:])
even_arr = arr[arr % 2 == 0]
print("Even numbers in the array:\n", even_arr)

First 2 rows:
 [[29 33 29 28 20 44]
 [17 30 39 35 50 38]]
Last 3 columns:
 [[28 20 44]
 [35 50 38]
 [42 24 22]
 [ 9  4 16]
 [19 35 26]
 [43 41  8]]
Even numbers in the array:
 [28 20 44 30 50 38 48 42 24 22 50 12  4 16 22 10 26 20 36  8]


**3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.**

In [84]:
reshape_arr = arr.reshape(3, 2, 6)
print("Reshaped array:\n", reshape_arr)
flattened = reshape_arr.flatten()
print("Flattened array:\n", flattened)

Reshaped array:
 [[[29 33 29 28 20 44]
  [17 30 39 35 50 38]]

 [[48  5 13 42 24 22]
  [11 50 12  9  4 16]]

 [[22 27 10 19 35 26]
  [20 36 11 43 41  8]]]
Flattened array:
 [29 33 29 28 20 44 17 30 39 35 50 38 48  5 13 42 24 22 11 50 12  9  4 16
 22 27 10 19 35 26 20 36 11 43 41  8]


**4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.**

In [90]:
identity_arr = np.eye(4)
print("Identity matrix (4x4):\n", identity_arr)
diagonal = np.diag([10, 20, 30, 40])
print("Identity matrix with 10, 20, 30, 40 as the diagonal:\n", diagonal)

Identity matrix (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Identity matrix with 10, 20, 30, 40 as the diagonal:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


**5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10).**

In [94]:
arr_a = np.random.randint(1, 11, size=(3, 4))
print(arr_a)

arr_b = np.random.randint(1, 11, size=(4, 3))
print(arr_b)
result = arr_a @ arr_b      # OR: result = np.dot(arr_a, arr_b)
print(result)

[[ 8  1  9  5]
 [ 4 10  1  3]
 [ 4 10  1  2]]
[[ 4  3  2]
 [ 8  7  2]
 [ 8  9  5]
 [10  3 10]]
[[162 127 113]
 [134 100  63]
 [124  97  53]]


**6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.**

In [89]:
def numpy_2D(arr):
    return np.where(arr % 2 ==0, arr ** 2, -1)

arr_input = np.arange(1, 17).reshape(4, 4)
print("Original array:\n", arr_input)
print("Array with function:\n", numpy_2D(arr_input))

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array with function:
 [[ -1   4  -1  16]
 [ -1  36  -1  64]
 [ -1 100  -1 144]
 [ -1 196  -1 256]]
