In [2]:
import numpy as np

In [3]:
# Define matrices A and B
A = np.array([[2, -1],
              [0,  3]])
B = np.array([[1,  4],
              [-2, 5]])

c, d = 2, 3  # Scalars

# (a) Scalar multiplications
cA = c * A
dB = d * B
sumA = (c + d) * A

print("cA =\n", cA)
print("dB =\n", dB)
print("(c+d)A =\n", sumA)



cA =
 [[ 4 -2]
 [ 0  6]]
dB =
 [[ 3 12]
 [-6 15]]
(c+d)A =
 [[10 -5]
 [ 0 15]]


In [4]:
# (b) Verify scalar multiplication properties
# Associativity: (cd)A == c(dA)
left = (c * d) * A
dA = d * A
right = c * dA
print("\nAssociativity check:\nLeft =\n", left, "\nRight =\n", right)

# Distributivity over addition: c(A + B) == cA + cB
LHS = c * (A + B)
cB = c * B
RHS = cA + cB
print("\nDistributivity over addition:\nLHS =\n", LHS, "\nRHS =\n", RHS)

# Distributivity over scalar addition: (c + d)A == cA + dA
left = (c + d) * A
right = cA + dA
print("\nDistributivity over scalar addition:\nLeft =\n", left, "\nRight =\n", right)





Associativity check:
Left =
 [[12 -6]
 [ 0 18]] 
Right =
 [[12 -6]
 [ 0 18]]

Distributivity over addition:
LHS =
 [[ 6  6]
 [-4 16]] 
RHS =
 [[ 6  6]
 [-4 16]]

Distributivity over scalar addition:
Left =
 [[10 -5]
 [ 0 15]] 
Right =
 [[10 -5]
 [ 0 15]]


In [5]:
# (c) Transposes
A_T = A.T
B_T = B.T
print("\nA^T =\n", A_T)
print("B^T =\n", B_T)




A^T =
 [[ 2  0]
 [-1  3]]
B^T =
 [[ 1 -2]
 [ 4  5]]


In [6]:
# (d) Determinants and Inverses
detA = round(np.linalg.det(A))
detB = round(np.linalg.det(B))
print("\nDet(A) =", detA)
print("Det(B) =", detB)

A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
print("\nA inverse =\n", A_inv)
print("B inverse =\n", B_inv)


Det(A) = 6
Det(B) = 13

A inverse =
 [[0.5        0.16666667]
 [0.         0.33333333]]
B inverse =
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
