In [1]:
import numpy as np

Exercise 1: Create a 5×4 Matrix and Compute Totals & Averages
```c
Defining the scores of 5 students across 4 subjects (Math, English, Science, Economics).

Representing the scores of 5 students in 4 subjects (Math, English, Science, Economics) as a 5×4 dataset:

Student 1 → 80, 70, 90, 85
Student 2 → 60, 85, 75, 70
Student 3 → 95, 88, 92, 96
Student 4 → 70, 60, 65, 72
Student 5 → 85, 78, 80, 88

In [2]:
# Compute total score per student (row sum).

# Compute average score per subject (column mean).

# Matrix of scores (5 students × 4 subjects)
scores = np.array([
    [80, 70, 90, 85],
    [60, 85, 75, 70],
    [95, 88, 92, 96],
    [70, 60, 65, 72],
    [85, 78, 80, 88]
])

# Total score per student (row sums)
student_totals = np.sum(scores, axis=1)
print("\nTotal score per student (row sums):")
student_totals




Total score per student (row sums):


array([325, 290, 371, 267, 331])

In [3]:
# Average score per subject (column means)
subject_averages = np.mean(scores, axis=0)
print("\nAverage score per subject (column means):")
subject_averages


Average score per subject (column means):


array([78. , 76.2, 80.4, 82.2])

Exercise 2: Make Economics 3× More Important
```c
Applying scalar multiplication: multiply the Economics column (3rd subject) by 3.

Total Score per Student (Row Sum)

To find the total score for each student, we sum across the subjects:
Adjusting Importance of Economics (4th Subject ×3)

We multiply all values in the 4th column by 3:

Student 1 → 80, 70, 90, 255
Student 2 → 60, 85, 75, 210
Student 3 → 95, 88, 92, 288
Student 4 → 70, 60, 65, 216
Student 5 → 85, 78, 80, 264

New Totals after Adjustment

Student 1 → 80 + 70 + 90 + 255 = 495
Student 2 → 60 + 85 + 75 + 210 = 430
Student 3 → 95 + 88 + 92 + 288 = 563
Student 4 → 70 + 60 + 65 + 216 = 411
Student 5 → 85 + 78 + 80 + 264 = 507

In [4]:
# Copy original matrix
new_scores = scores.copy()

# Multiply Science column (index 2) by 3
new_scores[:, 3] = new_scores[:, 3] * 3

new_scores

# Recompute totals
new_totals = np.sum(new_scores, axis=1)

new_totals


array([495, 430, 563, 411, 507])

Exercise 3: New Grading Weights (40%, 20%, 30%, 10%)
```c
weights vector (w) = [0.4, 0.2, 0.3, 0.1]
Final_grade = Matrix multiplication:
                                    G = Axw^T


Where: 
    𝐺 is a column vector of grades (one per student).

Final Grades Using Weights

We assign weights to each subject:

Math = 0.4
English = 0.2
Science = 0.3
Economics = 0.1

The final grade for each student is computed as:

Final Grade = (Math × 0.4) + (English × 0.2) + (Science × 0.3) + (Economics × 0.1)

Example (Student 1):
(80 × 0.4) + (70 × 0.2) + (90 × 0.3) + (85 × 0.1)
= 32 + 14 + 27 + 8.5 = 81.5

Results for all students:

Student 1 → 81.5
Student 2 → 70.5
Student 3 → 92.8
Student 4 → 66.7
Student 5 → 82.4

Final Grades = 81.5, 70.5, 92.8, 66.7, 82.4

In [5]:
# Define weights
weights = np.array([0.4, 0.2, 0.3, 0.1])

# Compute final grades using matrix multiplication
final_grades = scores @ weights

final_grades


array([81.5, 70.5, 92.8, 66.7, 82.4])

Exercise 4: Compare Student 3 & Student 4 (Vector Subtraction)
```c
Compare scores of Student 3 and Student 4 across subjects:

Comparison = Student 3 - Student 4

Student 3 scores: 95, 88, 92, 96
Student 4 scores: 70, 60, 65, 72

Compute the difference (Student 3 − Student 4) for each subject:

Math: 95 − 70 = 25

English: 88 − 60 = 28

Science: 92 − 65 = 27

Economics: 96 − 72 = 24

Differences = 25, 28, 27, 24

Interpretation:

A positive difference means Student 3 scored higher than Student 4 in that subject.

Student 3 outperformed Student 4 in all four subjects.

The largest margin is in English (28 points), followed by Science (27), Math (25), and Economics (24).

Conclusion

Overall, Student 3 performs consistently better than Student 4 across every subject, with the biggest advantage in English.


In [6]:
# Extract student 3 and student 4 (index 2 and 3)
student3 = scores[2]
student4 = scores[3]

# Vector subtraction
# comparison = student3 - student4
comparison = np.subtract(student3, student4)
comparison

# Note: Student 3 performed better than Student 4

array([25, 28, 27, 24])

3.1 Representing Data as a Matrix
```c
A = [[80, 70, 90],
     [60, 85, 75],
     [95, 88, 92],
     [70, 60, 65]
    ]

(rows = students, columns = Math, English, Science).    

In [1]:
import numpy as np

# Matrix of scores (rows = students, columns = [Math, English, Science])
A = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [95, 88, 92],
    [70, 60, 65]
])

A


array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

3.2 Total Scores per Student (Row Sum)

```c
Step-by-step sums:
Student 1: 80 + 70 + 90 = 240
Student 2: 60 + 85 + 75 = 220
Student 3: 95 + 88 + 92 = 275
Student 4: 70 + 60 + 65 = 195


In [2]:
totals = A.sum(axis=1)   # sum across rows
totals


array([240, 220, 275, 195])

3.3 Applying Weights (Scalar Multiplication)
```c
Suppose the weights are:

Math = 2 (twice as important),

English = 1,

Science = 1.

Student 1: 160 + 70 + 90 = 320
Student 2: 120 + 85 + 75 = 280
Student 3: 190 + 88 + 92 = 370
Student 4: 140 + 60 + 65 = 265

This shows how weighting changes the ranking:

Student 3 (370) > Student 1 (320) > Student 2 (280) > Student 4 (265)

In [3]:
weights = np.array([2, 1, 1])   # Math is twice as important
A_weighted = A * weights
weighted_totals = A_weighted.sum(axis=1)
A_weighted, weighted_totals


(array([[160,  70,  90],
        [120,  85,  75],
        [190,  88,  92],
        [140,  60,  65]]),
 array([320, 280, 370, 265]))

3.4 Average Score per Subject (Column Mean)
```c
Math column: 80 + 60 + 95 + 70 = 305
English column: 70 + 85 + 88 + 60 = 303
Science column: 90 + 75 + 92 + 65 = 322
So column totals = [305, 303, 322]

Math: 305 ÷ 4 = 76.5
English: 303 ÷ 4 = 75.75
Science: 322 ÷ 4 = 80.5

Averages = [76.5, 75.75, 80.5]

In [4]:
averages = A.mean(axis=0)   # mean across columns
averages


array([76.25, 75.75, 80.5 ])

3.5 Final Grades (Matrix Multiplication with Weights)



In [5]:
w = np.array([0.5, 0.3, 0.2])   # subject weights
final_grades = A.dot(w)
final_grades


array([79. , 70.5, 92.3, 66. ])

3.6 Comparing Students (Vector Subtraction)

Example: Compare Student 1 vs Student 2

Interpretation:

Student 1 is +20 higher in Math, -15 lower in English, +15 higher in Science.

Overall distance between them ≈ 29.15.

In [6]:
diff_1_2 = A[0] - A[1]   # Student1 - Student2
dist_1_2 = np.linalg.norm(diff_1_2)
diff_1_2, dist_1_2


(array([ 20, -15,  15]), 29.154759474226502)