Exercise 1: Create a 5×4 Matrix and Compute Totals & Averages

We define the scores of 5 students across 4 subjects (Math, English, Science, Physics).

In [2]:
import numpy as np

In [6]:
# Compute total score per student (row sum).

# Compute average score per subject (column mean).

# Matrix of scores (5 students × 4 subjects)
scores = np.array([
    [80, 70, 90, 85],
    [60, 85, 75, 70],
    [95, 88, 92, 96],
    [70, 60, 65, 72],
    [85, 78, 80, 88]
])

# Total score per student (row sums)
student_totals = np.sum(scores, axis=1)
print("\nTotal score per student (row sums):")
student_totals






Total score per student (row sums):


array([325, 290, 371, 267, 331])

In [5]:
# Average score per subject (column means)
subject_averages = np.mean(scores, axis=0)
print("\nAverage score per subject (column means):")
subject_averages


Average score per subject (column means):


array([78. , 76.2, 80.4, 82.2])

Exercise 2: Make Science 3× More Important

We apply scalar multiplication: multiply the Physics column (3rd subject) by 3.

In [13]:
# Copy original matrix
physics_scores = scores.copy()

# Multiply Science column (index 2) by 3
physics_scores[:, 3] = physics_scores[:, 3] * 3

physics_scores

# Recompute totals
physics_totals = np.sum(physics_scores, axis=1)

physics_totals


array([495, 430, 563, 411, 507])