In [2]:
import numpy as np

Exercise 1: Create a 5×4 Matrix and Compute Totals & Averages
```c
Defining the scores of 5 students across 4 subjects (Math, English, Science, Economics).

Representing the scores of 5 students in 4 subjects (Math, English, Science, Economics) as a 5×4 dataset:

Student 1 → 80, 70, 90, 85
Student 2 → 60, 85, 75, 70
Student 3 → 95, 88, 92, 96
Student 4 → 70, 60, 65, 72
Student 5 → 85, 78, 80, 88

In [ ]:
# Compute total score per student (row sum).

# Compute average score per subject (column mean).

# Matrix of scores (5 students × 4 subjects)
scores = np.array([
    [80, 70, 90, 85],
    [60, 85, 75, 70],
    [95, 88, 92, 96],
    [70, 60, 65, 72],
    [85, 78, 80, 88]
])

# Total score per student (row sums)
student_totals = np.sum(scores, axis=1)
print("\nTotal score per student (row sums):")
student_totals




Total score per student (row sums):


array([325, 290, 371, 267, 331])

In [5]:
# Average score per subject (column means)
subject_averages = np.mean(scores, axis=0)
print("\nAverage score per subject (column means):")
subject_averages


Average score per subject (column means):


array([78. , 76.2, 80.4, 82.2])

Exercise 2: Make Economics 3× More Important
```c
Applying scalar multiplication: multiply the Economics column (3rd subject) by 3.

Total Score per Student (Row Sum)

To find the total score for each student, we sum across the subjects:
Adjusting Importance of Economics (4th Subject ×3)

We multiply all values in the 4th column by 3:

Student 1 → 80, 70, 90, 255
Student 2 → 60, 85, 75, 210
Student 3 → 95, 88, 92, 288
Student 4 → 70, 60, 65, 216
Student 5 → 85, 78, 80, 264

New Totals after Adjustment

Student 1 → 80 + 70 + 90 + 255 = 495
Student 2 → 60 + 85 + 75 + 210 = 430
Student 3 → 95 + 88 + 92 + 288 = 563
Student 4 → 70 + 60 + 65 + 216 = 411
Student 5 → 85 + 78 + 80 + 264 = 507

In [14]:
# Copy original matrix
new_scores = scores.copy()

# Multiply Science column (index 2) by 3
new_scores[:, 3] = new_scores[:, 3] * 3

new_scores

# Recompute totals
new_totals = np.sum(new_scores, axis=1)

new_totals


array([495, 430, 563, 411, 507])

Exercise 3: New Grading Weights (40%, 20%, 30%, 10%)
```c
weights vector (w) = [0.4, 0.2, 0.3, 0.1]
Final_grade = Matrix multiplication:
                                    G = Axw^T


Where: 
    𝐺 is a column vector of grades (one per student).

Final Grades Using Weights

We assign weights to each subject:

Math = 0.4
English = 0.2
Science = 0.3
Economics = 0.1

The final grade for each student is computed as:

Final Grade = (Math × 0.4) + (English × 0.2) + (Science × 0.3) + (Economics × 0.1)

Example (Student 1):
(80 × 0.4) + (70 × 0.2) + (90 × 0.3) + (85 × 0.1)
= 32 + 14 + 27 + 8.5 = 81.5

Results for all students:

Student 1 → 81.5
Student 2 → 70.5
Student 3 → 92.8
Student 4 → 66.7
Student 5 → 82.4

Final Grades = 81.5, 70.5, 92.8, 66.7, 82.4

In [15]:
# Define weights
weights = np.array([0.4, 0.2, 0.3, 0.1])

# Compute final grades using matrix multiplication
final_grades = scores @ weights

final_grades


array([81.5, 70.5, 92.8, 66.7, 82.4])

Exercise 4: Compare Student 3 & Student 4 (Vector Subtraction)
```c
Compare scores of Student 3 and Student 4 across subjects:

Comparison = Student 3 - Student 4

Student 3 scores: 95, 88, 92, 96
Student 4 scores: 70, 60, 65, 72

Compute the difference (Student 3 − Student 4) for each subject:

Math: 95 − 70 = 25

English: 88 − 60 = 28

Science: 92 − 65 = 27

Economics: 96 − 72 = 24

Differences = 25, 28, 27, 24

Interpretation:

A positive difference means Student 3 scored higher than Student 4 in that subject.

Student 3 outperformed Student 4 in all four subjects.

The largest margin is in English (28 points), followed by Science (27), Math (25), and Economics (24).

Conclusion

Overall, Student 3 performs consistently better than Student 4 across every subject, with the biggest advantage in English.


In [17]:
# Extract student 3 and student 4 (index 2 and 3)
student3 = scores[2]
student4 = scores[3]

# Vector subtraction
comparison = student3 - student4

comparison

# Note: Student 3 performed better than Student 4

array([25, 28, 27, 24])