##### Topic: Linear Algebra
**Class Task 2**

**Question**
```c
Given the following matrices:
A = [[2, -1, 3], [0, 4, 1]]
B = [[1, 2], [-2, 0], [5, -3]]
```

```
a) Identify the number of rows and columns in each matrix.
b) Determine whether the matrices can be multiplied. If so, specify whether it's (AB), (BA), or both.
c) If the multiplication is defined, compute the resulting matrix.
```

##### Solution

**a) Identify the number of rows and columns in each matrix.**
```c
- A has 2 rows and 3 columns --> 2x3.
- B has 3 rows and 2 columns --> 3x2.
```

**b) Determine whether the matrices can be multiplied. If so, specify whether it's (AB), (BA), or both.**
```c
- AB is defined because A's 3 columns = B's 3 rows. And the result will be 2x2.
- BA is defined because B's 2 columns = A's 2 rows. And the result will be 3x3.
- So, both (AB) and (BA) are defined.
```

**c) If the multiplication is defined, compute the resulting matrix.**
```c
AB = [[(2)(1) + (-1)(-2) + (3)(5),   (2)(2) + (-1)(0) + (3)(-3)], [(0)(1) + (4)(-2) + (1)(5),   (0)(2) + (4)(0) + (1)(-3)]]

AB = [[(2 + 2 + 15),  (4 + 0 - 9)], [(0 - 8 + 5),  (0 + 0 - 3)]]
AB = [[19, -5], [-3, -3]]



BA = [[(1)(2) + (2)(0),  (1)(-1) + (2)(4),  (1)(3) + (2)(1)], [(-2)(2) + (0)(0),  (-2)(-1) + (0)(4),  (-2)(3) + (0)(1)], [(5)(2) + (-3)(0),  (5)(-1) + (-3)(4),  (5)(3) + (-3)(1)]]

BA = [[(2), (-1 + 8), (3 + 2)], [(-4), (2), (-6)], [(10), (-5 - 12), (15 - 3)]]
BA = [[2, 7, 5], [-4, 2, -6], [10, -17, 12]]
```

##### Code that does the computation of the matrix in the task in numpy

In [2]:
# Matrix Multiplication

# import library
import numpy as np

In [ ]:
# Define matrices A and B
# a) Identify the number of rows and columns in each matrix.

A = np.array([[2, -1, 3], [0, 4, 1]])

B = np.array([[1, 2], [-2, 0], [5, -3]])

print("Matrix A:\n", A)
print("Shape of A:", A.shape)

print("\nMatrix B:\n", B)
print("Shape of B:", B.shape)

Matrix A:
 [[ 2 -1  3]
 [ 0  4  1]]
Shape of A: (2, 3)

Matrix B:
 [[ 1  2]
 [-2  0]
 [ 5 -3]]
Shape of B: (3, 2)


In [4]:
# b) Determine whether the matrices can be multiplied. If so, specify whether it's (AB), (BA), or both.

# Check conditions for matrix multiplication
rows_A, cols_A = A.shape
rows_B, cols_B = B.shape

print("Can we compute AB? ", "Yes" if cols_A == rows_B else "No")
print("If valid, AB will have shape:", (rows_A, cols_B))

print("\nCan we compute BA? ", "Yes" if cols_B == rows_A else "No")
print("If valid, BA will have shape:", (rows_B, cols_A))


Can we compute AB?  Yes
If valid, AB will have shape: (2, 2)

Can we compute BA?  Yes
If valid, BA will have shape: (3, 3)


In [ ]:
# c) If the multiplication is defined, compute the resulting matrix.

# Compute AB
AB = np.dot(A, B)
print("AB =\n", AB)
print("Shape of AB:", AB.shape)


AB =
 [[19 -5]
 [-3 -3]]
Shape of AB: (2, 2)


In [9]:
# Compute BA
BA = np.dot(B, A)
print("BA =\n", BA)
print("Shape of BA:", BA.shape)


BA =
 [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
Shape of BA: (3, 3)
